[package]
name = "hyde-backend"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"
description = "A backend for the r/TechSupport CMS"
repository = "https://github.com/r-Techsupport/hyde"
readme = "../README.md"
keywords = ["cms", "wiki"]
categories = ["server-backend"]


[dependencies]
axum = { version = "0.7.5", features = ["http2", "macros"] }
chrono = "0.4.38"
clap = { version = "4.5.7", features = ["derive"] }
color-eyre = "0.6.3"
dotenvy = "0.15.7"
env_logger = "0.11.3"
git2 = "0.19.0"
jsonwebtoken = "9.3.0"
log = "0.4.21"
oauth2 = "4.4.2"
reqwest = { version = "0.12.5", features = ["stream"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.119"
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread", "signal"] }
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["normalize-path", "fs", "cors"] }
